### ISSUE TITLE
MacOS/ Amazon Linux?

### ISSUE THREAD

**Issue by szitello** [Asymmetrik/fhir-facade-starter#15]
I tried installing in Docker for Mac but ran into build problems.  I expect I can ignore the warning but not the error.

> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ERROR: Service 'fhir' failed to build: The command '/bin/sh -c apt-get -y update' returned a non-zero code: 100

I am considering AWS Docker.  Has anyone had success there?

**Comment by jonterrylee** [comment]
@szitello 

I made a branch to update the docker image.  Can you see if this works for you?  We are building on Macs here and it looks ok for us.  Let me know if you're having any issues.

[updated docker branch](https://github.com/Asymmetrik/fhir-facade-starter/tree/feature/update-docker)

**Comment by szitello** [comment]
Thanks for the help.  That gets me most of the way there.
However, #docker-compose up still throws errors:

Starting fhir-facade-starter-feature-update-docker_fhir_1 ... done

Attaching to fhir-facade-starter-feature-update-docker_fhir_1

fhir_1  | yarn run v1.16.0

fhir_1  | $ cross-env NODE_ENV=development; node scripts/nodemon;

fhir_1  | internal/modules/cjs/loader.js:638

fhir_1  |     throw err;

fhir_1  |     ^

fhir_1  |

fhir_1  | Error: Cannot find module 'nodemon'

fhir_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

fhir_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

fhir_1  |     at Module.require (internal/modules/cjs/loader.js:690:17)

fhir_1  |     at require (internal/modules/cjs/helpers.js:25:18)

fhir_1  |     at Object.<anonymous> (/srv/scripts/nodemon.js:1:17)

fhir_1  |     at Module._compile (internal/modules/cjs/loader.js:776:30)

fhir_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

fhir_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)

fhir_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

fhir_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

fhir_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

fhir_1  | error Command failed with exit code 1.

fhir-facade-starter-feature-update-docker_fhir_1 exited with code 1

I don’t know enough about docker to understand what’s wrong here:
#yarn nodemon
from command-line will start the server and show the 3_0_1/metadata, but I assume it’s not all the way “up”

**Comment by szitello** [comment]
OK.  I see.
Needed to change package.json:
Line 3:
 "scripts": {
    "start": "cross-env NODE_ENV=production; node src/index.js;",
    "nodemon": "cross-env NODE_ENV=development; node scripts/nodemon;",

To This:
 "scripts": {
    "start": "cross-env NODE_ENV=production; node src/index.js;",
    "nodemon": "cross-env NODE_ENV=development; node scripts/nodemon.js;",

Thanks again for your response.

From: Sean Zitello <sean.zitello@rhapsody.health>
Date: Tuesday, June 25, 2019 at 1:01 PM
To: Asymmetrik/fhir-facade-starter <reply@reply.github.com>, Asymmetrik/fhir-facade-starter <fhir-facade-starter@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: External:Re: [Asymmetrik/fhir-facade-starter] MacOS/ Amazon Linux? (#15)

Thanks for the help.  That gets me most of the way there.
However, #docker-compose up still throws errors:

Starting fhir-facade-starter-feature-update-docker_fhir_1 ... done

Attaching to fhir-facade-starter-feature-update-docker_fhir_1

fhir_1  | yarn run v1.16.0

fhir_1  | $ cross-env NODE_ENV=development; node scripts/nodemon;

fhir_1  | internal/modules/cjs/loader.js:638

fhir_1  |     throw err;

fhir_1  |     ^

fhir_1  |

fhir_1  | Error: Cannot find module 'nodemon'

fhir_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

fhir_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)

fhir_1  |     at Module.require (internal/modules/cjs/loader.js:690:17)

fhir_1  |     at require (internal/modules/cjs/helpers.js:25:18)

fhir_1  |     at Object.<anonymous> (/srv/scripts/nodemon.js:1:17)

fhir_1  |     at Module._compile (internal/modules/cjs/loader.js:776:30)

fhir_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

fhir_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)

fhir_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

fhir_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

fhir_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

fhir_1  | error Command failed with exit code 1.

fhir-facade-starter-feature-update-docker_fhir_1 exited with code 1

I don’t know enough about docker to understand what’s wrong here:
#yarn nodemon
from command-line will start the server and show the 3_0_1/metadata, but I assume it’s not all the way “up”

**Comment by szitello** [comment]
Sorry for mis-information.  The change I specified above actually does not resolve that Docker startup issue.  But can say  closed anyways since the Node run start method does work fine.
