### ISSUE TITLE
Issue with passport BasicStrategy

### ISSUE THREAD

**Issue by jamsheer-thottathil** [Asymmetrik/fhir-facade-starter#3]
I need to authenticate my request with some predefined credential.
So that I have tried to implement with BasicStrategy , but I am getting permission denied issue.

**Please see sample code**

**config.js**

```
	auth: {
		
		
		strategy: {
		 	name: 'basic',
			 useSession: false,
		 	service: './src/strategies/basic.strategy.js'
		 },
	},

```

**basic.strategy.js**

```
module.exports.strategy = new BasicStrategy(	
	function(username, password, done) {		
		User.findOne({ username: username }, function (err, user) {			
			return done(null, true);
		});
		return done(null, false);
	  }
);

```

**Comment by Robert-W** [comment]
Hi @jamsheer-thottathil, We will try to take a look at this today and see if we can figure out what's happening. Thanks for reporting this.

**Comment by jamsheer-thottathil** [comment]
@Robert-W  thank you for your response.  :)


Are expecting any specific format for the response?

It worked to me when I commented the validation in the core.

https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/utils/scope.utils.js
In above file line 45 changed as  return next();

**Comment by jonterrylee** [comment]
@jamsheer-thottathil 

The response needs to be formatted in a certain way.  I am making a change so we only need to pass back one user object.

Take a look at this PR
[94](https://github.com/Asymmetrik/node-fhir-server-core/pull/94)

You can use this branch for now and it should work.
in your package.json
"@asymmetrik/node-fhir-server-core": "git+https://github.com/Asymmetrik/node-fhir-server-core.git#feature/passport-user",


In your basic.strategy.js you need to return a scope most importantly.  Here is an example:
return done(null, { user_id: username, scope: 'patient/*.*' });

Scopes are based on the SMART spec.
http://docs.smarthealthit.org/authorization/scopes-and-launch-context/

Let me know if this works for you.

**Comment by jamsheer-thottathil** [comment]
ok @jonterrylee 
Thank you for the reply. I will update you after checking it.

**Comment by jamsheer-thottathil** [comment]
Yes, It worked for me, Thank You :)

**Comment by Robert-W** [comment]
Thanks @jamsheer-thottathil, let us know if you have any other questions. Im'm gonna mark this as resolved.

**Comment by jamsheer-thottathil** [comment]
You can close it 👍
