### ISSUE TITLE
Create composition is not working

### ISSUE THREAD

**Issue by razakpm** [Asymmetrik/fhir-facade-starter#5]
I have tried to POST with  https://zzzzzabc.com/3_0_1/composition with content type application/fhir+json and body as data from https://www.hl7.org/fhir/composition-example.json.html

We are getting the following error 

 {
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td><pre>'resourceType' expected to have value of 'Composition', received 'undefined'</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "'resourceType' expected to have value of 'Composition', received 'undefined'"
        }
    ]
}

It is working fine for search composition

**Comment by jonterrylee** [comment]
@razakpm 

We had the fix for this in another branch that was just merged in to the repo.  Can you update your dependencies and try again?  It should work now.

Thanks

**Comment by razakpm** [comment]
@jonterrylee 
Thanks, will check and get back soon

**Comment by razakpm** [comment]
@jonterrylee 
Thanks, everything working fine
