### ISSUE TITLE
composition: searchById is not working

### ISSUE THREAD

**Issue by JayakrishnanJK** [Asymmetrik/fhir-facade-starter#7]
We are trying to get composition  resource data using searchById method.  But it is showing some error like "Cannot read property 'versionId' of undefined"

While trying to resolve composition_resource using resolve like below.
`	resolve(composition_resource);
` 
But It is not showing response for test value for resource "composition_resource.id = 'test id';".

we are getting following error response. 

`
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td><pre>Cannot read property 'versionId' of undefined</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "exception",
            "diagnostics": "Cannot read property 'versionId' of undefined"
        }
    ]
}`

Please guide on this.

**Comment by jonterrylee** [comment]
Hi @JayakrishnanJK 

Does your response have a meta attribute?  The response needs to add the Etag and location headers that needs the version ID.

The response should look something like this
```javascript
{
	resourceType: "Composition",
	meta: {
		versionId: "1",
		lastUpdated: "2018"
	}
	.
	.
	.
}
```

**Comment by JayakrishnanJK** [comment]
Thanks. Its worked.

**Comment by PedroS11** [comment]
And how do we fill the information about the versionId?

I tried
`composition_resource.meta.versionId = 1 
`
But meta is undefined

**Comment by PedroS11** [comment]
Nevermind, I got it
`composition_resource.meta = { versionId="1"}`
