### ISSUE TITLE
Error in patient search with organization as parameter.

### ISSUE THREAD

**Issue by JayakrishnanJK** [Asymmetrik/fhir-facade-starter#8]
While trying to search with organization as search parameter. it showing following error. Please help on this.   

`{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td><pre>Invalid parameter: organization</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Invalid parameter: organization"
        }
    ]
}`

**Comment by JayakrishnanJK** [comment]
@jonterrylee  any help on this?

**Comment by jonterrylee** [comment]
Sorry i thought this was resolved by a team member.  I'm double checking now.  Sorry for the delay

**Comment by jonterrylee** [comment]
@JayakrishnanJK 

We have a fix for this in our develop branch.  We'll try to get that merged in today.

If you like you can update your dependency for develop and see if that fixes your issue.

```javascript
"dependencies": {
    "@asymmetrik/node-fhir-server-core": "git+https://github.com/Asymmetrik/node-fhir-server-core.git#develop",
    .
    .
    .
  },
```

Our team thought they had notified you on the progress, sorry for the miscommunication.

**Comment by PedroS11** [comment]
Any eta for the merge to master branch?

**Comment by jonterrylee** [comment]
@PedroS11 @JayakrishnanJK 

It should be merged in now.  Please let me know if you're still having issues.

**Comment by PedroS11** [comment]
You can close it, now it's fine :D
